import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("graph-core keeps renderer data typed through RenderableGraph", async () => {
  const source = await readFile(new URL("../src/index.ts", import.meta.url), "utf8");
  assert.match(source, /RenderableGraph/);
  assert.match(source, /setData\(data: RenderableGraph\)/);
  assert.match(source, /planGraphRender/);
  assert.match(source, /DEFAULT_GRAPH_RENDER_LIMITS/);
  assert.match(source, /omittedNodeCount/);
  assert.match(source, /GraphSummary/);
  assert.match(source, /nodeKindCounts/);
  assert.match(source, /topNodes/);
  assert.match(source, /extractNeighborhood/);
  assert.match(source, /DEFAULT_GRAPH_NEIGHBORHOOD_OPTIONS/);
  assert.match(source, /omittedEdgeCount/);
  assert.match(source, /findShortestPath/);
  assert.match(source, /DEFAULT_GRAPH_PATH_OPTIONS/);
  assert.match(source, /pathFound/);
  assert.match(source, /applyGraphLens/);
  assert.match(source, /nodeMatchesLens/);
  assert.match(source, /edgeMatchesLens/);
  assert.match(source, /resolveGraphVisualStates/);
  assert.match(source, /deriveGraphActivityEvents/);
  assert.match(source, /selectGraphAnimationBudget/);
  assert.match(source, /buildGraphTooltipModel/);
  assert.match(source, /buildGraphTetherPlan/);
  assert.match(source, /GraphAnimationBudget/);
  assert.match(source, /GraphVisualStateOptions/);
  assert.match(source, /GraphActivityDerivationInput/);
  assert.match(source, /GraphTetherPlan/);
  assert.match(source, /sensedIds/);
  assert.match(source, /slaAtRiskIds/);
  assert.match(source, /actionProposedIds/);
  assert.match(source, /outcomeSucceededIds/);
  assert.match(source, /feedbackAppliedIds/);
  assert.match(source, /full_motion/);
  assert.match(source, /reduced_motion/);
  assert.match(source, /sampled_graph/);
});
